In [1]:
import torch

In [10]:
#empty tensor
x = torch.empty(5,3)
print(x)

tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38],
        [9.6429e-39, 9.2755e-39, 9.7346e-39],
        [1.0745e-38, 1.0102e-38, 9.9184e-39]])


In [3]:
#random init
x = torch.rand(5,3)
print(x)

tensor([[0.9274, 0.2922, 0.4086],
        [0.6355, 0.2519, 0.8080],
        [0.4403, 0.4958, 0.5786],
        [0.9660, 0.0985, 0.2365],
        [0.7625, 0.3096, 0.2583]])


In [4]:
#zero and long type
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
#
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      
# new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)

# override dtype!
print(x)

# result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.0912, -1.1249, -0.2782],
        [-0.9492,  0.2929, -0.5252],
        [-0.0819, -0.4138, -1.3509],
        [-0.4980,  0.1304,  2.5223],
        [-0.1272, -1.2293, -0.1664]])


In [9]:
#add
y = torch.rand(5,3)
print(x+y)
print(torch.add(x,y))
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 2.3340, -0.4519,  0.5002],
        [-0.3320,  1.0181,  0.4141],
        [ 0.4160,  0.5123, -0.7420],
        [-0.2941,  0.8343,  3.1804],
        [ 0.6462, -0.7257,  0.4823]])
tensor([[ 2.3340, -0.4519,  0.5002],
        [-0.3320,  1.0181,  0.4141],
        [ 0.4160,  0.5123, -0.7420],
        [-0.2941,  0.8343,  3.1804],
        [ 0.6462, -0.7257,  0.4823]])
tensor([[ 2.3340, -0.4519,  0.5002],
        [-0.3320,  1.0181,  0.4141],
        [ 0.4160,  0.5123, -0.7420],
        [-0.2941,  0.8343,  3.1804],
        [ 0.6462, -0.7257,  0.4823]])


In [11]:
#change shape
x = torch.randn(4,4)
print(x.view(16))
print(x.view(4,2,2))

tensor([-0.7442, -1.3060, -0.5225, -1.0577,  0.0253,  0.2748, -0.1371,  0.2808,
        -1.0502,  0.0616, -0.3357,  1.2899,  2.6178, -1.0529, -1.0069, -0.2950])
tensor([[[-0.7442, -1.3060],
         [-0.5225, -1.0577]],

        [[ 0.0253,  0.2748],
         [-0.1371,  0.2808]],

        [[-1.0502,  0.0616],
         [-0.3357,  1.2899]],

        [[ 2.6178, -1.0529],
         [-1.0069, -0.2950]]])


In [14]:
#get the value
print(x[0,1].item())

-1.3060381412506104
